### ISSUE TITLE
Add support for cmpt tiles

### ISSUE THREAD

**Issue by RubioV** [Geodan/mapbox-3dtiles#1]
Add support for composite tiles, according to https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#introduction

**Comment by bertt** [comment]
created a composite test set see  https://bertt.github.io/mapbox_3dtiles_samples/samples/composite/amsterdam/index.html#18.14/52.373409/4.8922/0/45

All cmpt tiles contain 2 inner i3dm's (payload glTF is a box with and without animation)

Error currently displayed: cmpt tiles not yet implemented

**Comment by bertt** [comment]
fixed
