### ISSUE TITLE
Can I load oblique photography data?

### ISSUE THREAD

**Issue by limzgiser** [Geodan/mapbox-3dtiles#20]

**Comment by tomvantilburg** [comment]
Not sure what you mean by 'loading' the data. This plugin is meant for loading 3D-Tiles data which is likely not oblique photography, unless you mean textures on the buildings but that would be in the data already before loading.

**Comment by limzgiser** [comment]
Thank you for your answer.I have converted the  osgb  data to cesium 3d-tiles。
