### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by wubbzz** [Geodan/mapbox-3dtiles#24]
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://repo.geodan.io/repository/npm/mapbox-gl failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wbz\AppData\Roaming\npm-cache\_logs\2020-06-27T14_17_15_655Z-debug.log

**Comment by tomvantilburg** [comment]
Sorry, currently this library is not available on the public npm server. You can still install it from this git repo though.
