### ISSUE TITLE
Support RTC_CENTER in i3dm

### ISSUE THREAD

**Issue by bertt** [Geodan/mapbox-3dtiles#32]
For high precision instance positions in i3dm there should be support for RTC_CENTER in the featuretable.

Sample featuretable: {\"INSTANCES_LENGTH\":25,\"RTC_CENTER\":[1215013.8340490046,-4736316.75897742,4081608.4380407534],\"EAST_NORTH_UP\":true,\"POSITION\":{\"byteOffset\":0}}

Spec: https://github.com/CesiumGS/3d-tiles/tree/master/specification/TileFormats/Instanced3DModel#rtc_center

Should be similar to the RTC_CENTER functionality in pnts tiles.

**Comment by anneb** [comment]
Support added, to be tested with a i3dm that includes RTC_CENTER

**Comment by bertt** [comment]
fixed
