### ISSUE TITLE
Add boundingVolume.region support

### ISSUE THREAD

**Issue by bertt** [Geodan/mapbox-3dtiles#43]
Add boundingVolume.region support, see https://github.com/CesiumGS/3d-tiles/blob/master/specification/README.md#region

Pro's: smaller and more simple tileset.json

**Comment by tomvantilburg** [comment]
I think this is a duplicate of #4, no?

**Comment by bertt** [comment]
ah yes correct, extra upvote for that one :-) I'll close this issue.
